server:
  port: 8088

spring:
  application:
    name: ead-course-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ead-course
    username: course
    password: course
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
logging:
  level:
    com.rosivaldolucas.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service'

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
