services:
  db-ead-authuser:
    image: postgres:16.3-alpine3.20
    container_name: db-ead-authuser
    environment:
      POSTGRES_DB: ead-course
      POSTGRES_USER: course
      POSTGRES_PASSWORD: course
    ports:
      - 5432:5432
    volumes:
      - db-data-db-ead-course:/var/lib/postgresql/data

volumes:
  db-data-db-ead-course:
