server:
  port: 8081
  servlet:
    context-path: '/ead-authuser/'

spring:
  application:
    name: ead-authuser-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/db-ead-authuser
    username: ead-authuser
    password: ead-authuser
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
  
  rabbitmq:
    addresses: amqps://qimykxkr:njTxmKX4hMgucHdPys-NITUqrcY01_He@toad.rmq.cloudamqp.com/qimykxkr

logging:
  level:
    root: INFO
    com.rosivaldolucas.ead.authuser_api: TRACE
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      course-api: 'http://ead-course-service/ead-course'

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
