server:
  port: 8087

spring:
  application:
    name: authuser-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: authuser
    password: authuser
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    root: INFO
    com.rosivaldolucas.ead.authuser_api: TRACE
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      course-api: 'http://localhost:8087'
